// AUTO-GENERATED by: dotnet run --project Tools/DeterminismHarness golden
// Do not edit by hand. Regenerate only after a deliberate GenerationVersion bump.

namespace CatchIfYouCan.Procedural.Deterministic
{
    public static class GoldenSeedTable
    {
        public readonly struct Entry
        {
            public readonly int GenerationVersion;
            public readonly string MapDefinitionId;
            public readonly int Seed;
            public readonly string ExpectedHash;

            public Entry(int generationVersion, string mapDefinitionId, int seed, string expectedHash)
            {
                GenerationVersion = generationVersion;
                MapDefinitionId = mapDefinitionId;
                Seed = seed;
                ExpectedHash = expectedHash;
            }
        }

        public static readonly Entry[] Entries =
        {
            new Entry(1, "HOUSE_DEFAULT_A", 1, "DC8F181A6D4C5828"),
            new Entry(1, "HOUSE_DEFAULT_A", 7, "457D0C24443ABAFE"),
            new Entry(1, "HOUSE_DEFAULT_A", 42, "73D96355C252D5C8"),
            new Entry(1, "HOUSE_DEFAULT_A", 1337, "3745764C33049917"),
            new Entry(1, "HOUSE_DEFAULT_A", 184726392, "060E13EF6CF8D74A"),
            new Entry(1, "HOUSE_DEFAULT_A", 424242, "BEB989B64C42E81E"),
            new Entry(1, "HOUSE_DEFAULT_A", 999983, "31BA708DFE08F84F"),
            new Entry(1, "HOUSE_DEFAULT_A", -1, "4D7496F1D06FED0A"),
            new Entry(1, "HOUSE_DEFAULT_A", -2147483648, "C770349815570127"),
            new Entry(1, "HOUSE_DEFAULT_A", 2147483647, "402DE7DF80EA74FA"),
            new Entry(1, "HOUSE_DEFAULT_A", 65536, "CD583E93D3BFD1DD"),
            new Entry(1, "HOUSE_DEFAULT_A", 123456789, "DE698707569E696A"),
            new Entry(1, "HOUSE_TRAINING_A", 1, "69349E8001FACA09"),
            new Entry(1, "HOUSE_TRAINING_A", 7, "6C1CDD471F212DEE"),
            new Entry(1, "HOUSE_TRAINING_A", 42, "3C7CA5FA9B0BA112"),
            new Entry(1, "HOUSE_TRAINING_A", 1337, "22603D2DFB23504B"),
            new Entry(1, "HOUSE_TRAINING_A", 184726392, "A0E00507A06FFA79"),
            new Entry(1, "HOUSE_TRAINING_A", 424242, "75A4218317568E41"),
            new Entry(1, "HOUSE_TRAINING_A", 999983, "A7AAD0900B7D3360"),
            new Entry(1, "HOUSE_TRAINING_A", -1, "3D6770F2F3537109"),
            new Entry(1, "HOUSE_TRAINING_A", -2147483648, "704E3DC89C473CB3"),
            new Entry(1, "HOUSE_TRAINING_A", 2147483647, "B801D7AB1C7B587C"),
            new Entry(1, "HOUSE_TRAINING_A", 65536, "4756C3DE9F393F5C"),
            new Entry(1, "HOUSE_TRAINING_A", 123456789, "5BF8E1B077B6E86D"),
        };
    }
}
