#!/usr/bin/env bash
#
# Writes down which asset guids belong to a purchased pack that is NOT in the repository.
#
# Two packs are bought, licensed per seat, and deliberately gitignored: the HQ Modular House
# interior and the Knife Entertainment portal pack. Scenes and catalogs in this project name
# their guids, and on a machine without the pack those guids resolve to nothing.
#
# That is indistinguishable, from inside the repository, from CLAUDE.md mistake 14: content
# deleted without deleting what pointed at it. Both are "a guid nothing declares". The
# difference is knowable only on a machine that HAS the pack, so this script is run there and
# its output is committed. check_asset_references.sh then reads it and can tell the two apart:
#
#   named here, pack absent   -> expected. The pack is a local dependency.
#   named here, pack present  -> the pack changed under us. Fail.
#   not named here            -> a project asset went missing. Fail. (Mistake 14.)
#
# It reads .meta files and writes one text file. It imports nothing, changes no setting, and
# touches no file inside a pack.
set -u

root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root" || exit 1

out="Docs/VENDOR_ASSET_MANIFEST.txt"
tmp="$out.tmp"

# The vendor roots, taken from .gitignore rather than repeated here: a root added to the
# ignore file and forgotten here would silently stop being covered.
roots=$(grep -E '^/Assets/.+/$' .gitignore | sed 's|^/||; s|/$||')

if [ -z "$roots" ]; then
  echo "no vendor roots found in .gitignore - nothing to write" >&2
  exit 1
fi

present=""
absent=""
while IFS= read -r r; do
  [ -z "$r" ] && continue
  if [ -d "$r" ]; then present="$present$r"$'\n'; else absent="$absent$r"$'\n'; fi
done <<< "$roots"

if [ -z "$present" ]; then
  echo "None of the vendor roots is in this working copy:" >&2
  sed '/^$/d; s/^/  /' <<< "$absent" >&2
  echo "Run this on the machine that has the purchased packs installed." >&2
  exit 1
fi

{
  echo "# Vendor asset manifest - guids that live in a purchased, gitignored pack."
  echo "#"
  echo "# Generated by Scripts/write_vendor_manifest.sh on a machine that has the packs."
  echo "# Committed so that CI, which does not have them, can tell an expected absence from"
  echo "# an asset that went missing. Regenerate it after installing or updating a pack."
  echo "#"
  echo "# One record per line:  <guid>  <path inside the pack>"
  echo "#"
} > "$tmp"

total=0
while IFS= read -r r; do
  [ -z "$r" ] && continue
  echo "" >> "$tmp"
  echo "## $r" >> "$tmp"
  n=0
  # -print0 / read -d '' so that the spaces in "HQ Modular House" survive.
  while IFS= read -r -d '' meta; do
    guid=$(sed -n 's/^guid: \([0-9a-f]\{32\}\)$/\1/p' "$meta" | head -1)
    [ -z "$guid" ] && continue
    asset=${meta%.meta}
    # A .meta whose asset is gone describes nothing; skip it rather than record a guid that
    # would then be reported as "the pack changed" on the very machine that has the pack.
    [ -e "$asset" ] || continue
    printf '%s  %s\n' "$guid" "$asset" >> "$tmp"
    n=$((n + 1))
  done < <(find "$r" -name '*.meta' -type f -print0)
  echo "#   $n asset(s)" >> "$tmp"
  total=$((total + n))
done <<< "$present"

if [ -n "$absent" ]; then
  echo "" >> "$tmp"
  echo "# NOT SCANNED - these roots are not in this working copy, so nothing here covers them:" >> "$tmp"
  while IFS= read -r r; do
    [ -z "$r" ] && continue
    echo "#   $r" >> "$tmp"
  done <<< "$absent"
fi

mv "$tmp" "$out"

echo "wrote $out"
echo "  $total guid(s) across:"
sed '/^$/d; s/^/    /' <<< "$present"
if [ -n "$absent" ]; then
  echo "  NOT covered (root not installed here):"
  sed '/^$/d; s/^/    /' <<< "$absent"
fi
echo ""
echo "Commit this file. Without it CI cannot tell a missing pack from a deleted asset."
